---
title: "caribouPopGrowthModel"
author: "Tati Micheletti", "Frances E.C. Stewart", "Eliot J.B. McIntire"
date: "31 March 2019"
output: pdf_document
---

# Usage

```{r module_usage}
library(SpaDES)

setPaths(modulePath = file.path("/home/tmichele/Documents/GitHub/NWT/modules"))
getPaths() # shows where the 4 relevant paths are

times <- list(start = 0, end = 10)

parameters <- list(
  #.progress = list(type = "text", interval = 1), # for a progress bar
  ## If there are further modules, each can have its own set of parameters:
  #module1 = list(param1 = value1, param2 = value2),
  #module2 = list(param1 = value1, param2 = value2)
)
modules <- list("caribouPopGrowthModel")
objects <- list()
inputs <- list()
outputs <- list()

caribous <- simInitAndSpades(times = times, params = parameters, modules = modules,
                 objects = objects)

```
# **POPULATION ANALYSES USING THE SPADES MODULE GROUP FOR NWT BOREAL WOODLAND CARIBOU (*Rangifer tarandus caribou*)**
## NWT Framework for projecting Boreal Woodland caribou populations (study area scale)

## *Tati Micheletti, University of British Columbia*
## *Frances E. C. Stewart, Canadian Forest Service, Natural Resouces Canada & School of Environmental Studies, University of Victoria*
## *Eliot J.B. McIntire, Canadian Forest Service, Natural Resources Canada & Faculty fo Forestry, University of British Columbia*

# **GENERAL INFORMATION**
# Events

*Moduleobjective:* plot and save both popultion growth rate and population size of woodland boreal caribou across the North West Territories. This module uses results from the *caribouRecDistRelationship* module to project caribou population growth rate (lambda) and population size (N) under changing landscape conditions outlined in other modules: anthropogenic features and fire. This is conducted on a yearly time step (i.e. upon each event) for 100 years.
### note: module currenly does not link to anthropogenic feature change (as of 2019-03-05)

## Plotting

This module plots changes in population growth (N) and changes in population growth rate (lambda) over the simulation period (100 years).

## Saving

NA

# Data dependencies

## Input data

How to obtain input data, and a description of the data required by the module.
If `sourceURL` is specified, `downloadData("caribouPopGrowthModel", "path/to/modules/dir")` may be sufficient.

Data for woodland boreal caribou in the North West Territories Taiga plains has been compiled from Environment Canada 2011 Scientific Report, and is provided as an input to the *caribouRecDistRelationship* module. We use the reported recruitment values of four study areas reported (EC 2011); GSA north, GSA south, Dehcho North, and Dehcho South. We did not use available information on the Cameron Hills study area (EC 2008) as this population is regularly monitored by the Alberta government rather than NWT government (Gov NWT 2019).

## Output data

The output of this module is the population growth (N) and population growth rate (lambda) of woodland boreal caribou, within the Taiga plains NWT, over the simulation period (100 years).

# Links to other modules

The inputs of this module are linked to anthropogenic and fire modules. The outputs of this module are not linked to any other module.

# Assumptions of this module - to be stated explicitly in written reports and publications

**1. For all models (MODEL OPTION 1 THROUGH 6)**
ASSUMPTION A: The statistical relationship between recruitment and the landscape described by ECCC 2012 is the correct relationship for NWT boreal caribou. (Model M3, recruitment ~ total disturbance; ECCC 2012 Table 56). This relationship was generated off of 24 data points of caribou study areas across Canada, and lacks information on study areas primarily driven by fire.

ASSUMPTION B: Adult female survival is constant. We used the ECCC 2012 recommended value of 0.85. We assume that this value applies to all local populations of boreal woodland caribou in the North West Territories.

## POPULATION MODELS - output N (population size; MODEL OPTIONS 1 AND 2)
ASSUMPTION C: Initial population of boreal caribou across the North West Territories Taiga Plains is 6731 individuals (James Hodgson pers. comm.; Gov NWT 2019)
Government of the Northwest Territories. 2019. A Framework for Boreal Caribou Range Planning: Revised Draft - Appendices. Environment and Natural Resources, Government of the Northwest Territories, Yellowknife, NT. 38 + ii pp.

**2. For logarithmic population growth models (MODEL OPTION 2):**
ASSUMPTION D: The carrying capacity of boreal caribou in the North West Territories Taiga Plains is 10,000 individuals 

ASSUMPTION E: The intrinsic rate (r) of increase of boreal caribou in the North West Territories Taiga Plains is 10% (r = 0.10; Sutherland et al. in prep). Currently obtained from Sutherland et al. (in prep) demonstrating that recruitment needs to be > 0.1 for annual population growth

**3. For stochastic population growth models (MODEL OPTION 4 THROUGH 6): - to do for future projects**
Still to be completed


## POPULATION GROWTH MODELS - output lambda (population growth rate)**
**1. For population growth model (MODEL OPTION 3)**
Calculation of lambda is based off of McLaughlin et al. (2003). This population growth model was also used in Sorrensen et al. (2006), and Hervieux et al. (2013).


# *REPORT*


# Literature Cited

EC 2008

EC 2011

EC 2012

Sutherland et al. in prep

McLaughlin et al. 2003

Sorrensen et al. 2006

Hervieux et al. 2013

Gov NWT 2019



